# Generated by Django 6.0.2 on 2026-02-14 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('clinic_owner', 'Clinic Owner'), ('lab_owner', 'Laboratory Owner / Dental Technician'), ('self_employed', 'Self-employed dentist'), ('buyer', 'Buyer'), ('dealer', 'Dealer'), ('agent', 'Agent'), ('other', 'Other')], max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('days', models.TextField(blank=True, null=True, verbose_name='Days and times to be contacted')),
                ('privacy1', models.BooleanField(default=False, verbose_name='Privacy policy accepted')),
                ('privacy2', models.BooleanField(default=False, verbose_name='Newsletter/Marketing consent')),
                ('source_form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
