# Generated by Django 6.0.2 on 2026-02-14 13:55

import submissions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('implantologists_speakers', 'Implantologists Speakers'), ('italy_abroad_agents', 'Italy/Abroad Agents'), ('dealer_distributors', 'Dealer-Distributors Italy/Abroad'), ('other', 'Other')], max_length=50)),
                ('hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact hours')),
                ('message', models.TextField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=submissions.models.cv_upload_path, verbose_name='CV/Resume')),
                ('privacy', models.BooleanField(default=False, verbose_name='Privacy policy accepted')),
                ('source_form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
